name: SAM Build/Deploy
on:
  push:
    branches:
      - main
  # Temporarily build on PR while we're debugging GHA
  pull_request:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # sam build
      - run: sam build -t sam.template.yaml --use-container

      # sam deploy
      - run: sam deploy -t sam.template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name weather-tracker-java-rds-lambda --s3-bucket ${{ secrets.AWS_S3_BUCKET }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}