name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'DB Password'
        required: true
        type: string
      username:
        description: 'DB Username'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        default: DEV
        type: choice
        options:
          - DEV
          - PROD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildZip

  plan:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Get to Terraform directory
      - name: Terraform directory
        run: cd terraform

      # Initialize Terraform
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      # Terraform Plan
      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan -var-file="${{ inputs.environment }}.tfvars" -var="db-password=${{ inputs.password }}" -var="db-username=${{ inputs.username }}"
        working-directory: ./terraform

      # Publish artifact
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-plan
          path: './terraform/tfplan'

  apply:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: published-plan
          path: './terraform'
      - name: Look for artifact
        run: ls -la ./terraform
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      # Terraform Apply
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
