name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'DB Password'
        required: true
        type: string
      username:
        description: 'DB Username'
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Get to Terraform directory
      - name: Terraform directory
        run: cd terraform

      # Initialize Terraform
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      # Terraform Plan
      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan -var="db-password=${{ inputs.password }}" -var="db-username=${{ inputs.username }}"
        working-directory: ./terraform

      # Publish artifact
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-plan
          path: './terraform/tfplan'

  apply:
    environment: DEV
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: published-plan
          path: './terraform/tfplan'
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform
      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      # Terraform Apply
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -var="db-password=${{ inputs.password }}" -var="db-username=${{ inputs.username }}" tfplan
        working-directory: ./terraform
